name: pocket_puff
description: A fun anti-mindfulness app - Pocket Puff
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For microphone input
  permission_handler: ^11.0.1
  mic_stream: ^0.7.2

  # For accelerometer/shake detection
  sensors_plus: ^6.1.2
  shake: ^3.0.0

  # For audio playback
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/mindful.mp3
